### ISSUE TITLE
Jawa / Solum doesn't exist

### ISSUE THREAD

**Issue by Matsv** [mcdevs/Burger#14]
Hey,

I tried to use this program, however I couldn't get it working. I'm not a Python expert so this might be my problem.

First I tried
`python setup.py install`
Output:
```
running install
running build
running build_py
error: package directory 'solum' does not exist
```

After that I tried to run the munch.py
`python munch.py --download`
Output:
```
Traceback (most recent call last):
  File "munch.py", line 134, in <module>
    all_toppings = import_toppings()
  File "munch.py", line 68, in import_toppings
    __import__("burger.toppings.%s" % topping)
  File "/home/adr/mc/burger/Burger-mc18/Burger/burger/toppings/packetinstructions.py", line 31, in <module>
    from jawa.util.descriptor import method_descriptor
ImportError: No module named jawa.util.descriptor
```

I looked inside the setup.py file, that uses a dependency 'solum' with a link to a non-existing github repository: http://github.com/TkTech/Solum

Could this be the issue?

Python version: Python 2.7.10
Also tried it with 'python3': Python 3.4.3+

Thanks

**Comment by Pokechu22** [comment]
I think the `setup.py` is from when solum was packaged within this repo and shouldn't actually be used anymore.  (Solum is an older library that's been replaced with jawa).

Download Jawa [here](https://github.com/tktech/jawa); alternatively you should be able to use `pip install git+https://github.com/TkTech/Jawa.git` if you have Pip installed.

**Comment by Matsv** [comment]
@Pokechu22 Thanks! That worked :smile:

**Comment by TkTech** [comment]
Reopening, because I do actually have to fix the `setup.py` :)

**Comment by Matsv** [comment]
:+1:
